export interface Project {
  id: string;
  name: string;
  description: string;
  program: string;
  tags: string[];
  rdLevel?: number;
  status: "draft" | "analyzing" | "completed";
  documentsCount: number;
  lastUpdated: string;
  criteria?: {
    novelty: string;
    uncertainty: string;
    creativity: string;
    systematic: string;
    transferable: string;
  };
}

export interface Program {
  id: string;
  name: string;
  description: string;
  projectCount: number;
  avgRdLevel: number;
  color: string;
}

export const programs: Program[] = [
  { id: "p1", name: "AI & Machine Learning", description: "Projects exploring novel ML architectures and applications", projectCount: 4, avgRdLevel: 78, color: "hsl(var(--pwc-orange))" },
  { id: "p2", name: "Green Energy", description: "Sustainable energy R&D initiatives", projectCount: 3, avgRdLevel: 65, color: "hsl(var(--pwc-tangerine))" },
  { id: "p3", name: "Biotech Research", description: "Biotechnology and pharmaceutical innovations", projectCount: 3, avgRdLevel: 82, color: "hsl(var(--pwc-rose))" },
  { id: "p4", name: "Advanced Materials", description: "Novel material science research projects", projectCount: 2, avgRdLevel: 71, color: "hsl(18, 60%, 55%)" },
];

const criteriaTexts = {
  nas: {
    novelty: "The project introduces a fundamentally new approach to neural architecture search by combining evolutionary strategies with gradient-based optimization. Unlike existing NAS methods that rely on fixed search spaces, this approach dynamically expands the search space based on intermediate results, which represents a significant departure from established techniques in the field. The technical documentation demonstrates that no prior work has combined these specific methodologies in this manner.",
    uncertainty: "Significant technical uncertainties were identified around whether the evolutionary-gradient hybrid approach would converge within practical timeframes. The team documented multiple failed attempts with different crossover operators before identifying a viable strategy. The outcome of applying this approach to edge deployment constraints was not predictable from existing knowledge, as prior NAS methods have not targeted sub-100ms inference latency on ARM architectures.",
    creativity: "The creative contribution lies in the novel formulation of the architecture search as a multi-objective optimization problem that simultaneously considers accuracy, latency, and memory footprint. The team developed an original encoding scheme for network architectures that enables more efficient exploration of the search space compared to traditional cell-based representations.",
    systematic: "The research followed a rigorous experimental methodology with clearly defined hypotheses, controlled experiments, and systematic ablation studies. Each modification to the search algorithm was tested against standardized benchmarks (ImageNet, CIFAR-100) with statistical significance testing. The team maintained detailed logs of all experiments, including negative results.",
    transferable: "The findings on hybrid evolutionary-gradient search have broad applicability beyond the specific domain of edge deployment. The encoding scheme developed could be applied to architecture search for other constrained environments such as embedded systems, mobile devices, or FPGA implementations. The methodology documentation is sufficiently detailed to enable reproduction by other research teams.",
  },
  fl: {
    novelty: "The federated learning framework introduces a new aggregation protocol that addresses the non-IID data distribution problem through a cluster-based approach. While federated learning itself is an established field, the specific combination of hierarchical clustering with secure aggregation has not been previously explored in the literature. However, individual components build upon well-known techniques.",
    uncertainty: "The primary uncertainty concerned whether the cluster-based aggregation would maintain model convergence guarantees under adversarial conditions. Testing revealed unexpected behavior when more than 30% of participants had highly skewed data distributions, requiring additional research into robust aggregation methods. The privacy guarantees under composition were also uncertain.",
    creativity: "The framework proposes an original trust scoring mechanism that dynamically adjusts the influence of each participant's updates based on historical contribution quality. This approach draws an creative parallel from reputation systems in peer-to-peer networks, adapting these concepts to the federated learning context in a way not previously attempted.",
    systematic: "Development followed a structured approach with formal privacy proofs, convergence analysis, and empirical validation across three distinct use cases. Each protocol modification was accompanied by updated security proofs. However, some edge cases in the adversarial model were identified late in the process and addressed reactively rather than systematically.",
    transferable: "The aggregation protocol is domain-agnostic and has been demonstrated across healthcare, financial, and manufacturing datasets. The trust scoring mechanism could be adapted for other distributed computing paradigms. Documentation includes implementation guides for three major ML frameworks.",
  },
  llm: {
    novelty: "The fine-tuning pipeline adapts existing LoRA and QLoRA techniques for the specific domain of legal document analysis. While the individual techniques are well-established, the contribution lies in the domain-specific data curation pipeline and the custom evaluation metrics designed for legal reasoning tasks. The novelty is incremental rather than fundamental.",
    uncertainty: "Key uncertainties included whether fine-tuned models would maintain factual accuracy on legal precedents and whether the models could handle the specialized terminology and reasoning patterns in patent law. Initial experiments showed concerning hallucination rates that required novel mitigation strategies involving retrieval-augmented generation.",
    creativity: "The project developed an original annotation framework that leverages the hierarchical structure of legal documents to create training data more efficiently. The approach to combining extractive and generative capabilities within a single fine-tuned model represents a creative solution to the dual requirements of legal document analysis.",
    systematic: "The pipeline follows a well-documented methodology from data collection through evaluation, with automated quality checks at each stage. Evaluation uses both automated metrics and expert legal review. The team conducted systematic comparisons against commercial legal AI tools and open-source alternatives.",
    transferable: "The fine-tuning methodology and evaluation framework could be adapted for other specialized professional domains such as medical, financial, or engineering documentation. The data curation pipeline is designed to be reusable. However, the domain-specific components would require significant rework for each new application area.",
  },
};

export const projects: Project[] = [
  { id: "1", name: "Neural Architecture Search v2", description: "Automated discovery of optimal neural network topologies for edge deployment", program: "AI & Machine Learning", tags: ["AI & Machine Learning", "Optimization", "Edge Computing"], rdLevel: 85, status: "completed", documentsCount: 12, lastUpdated: "2026-02-28", criteria: criteriaTexts.nas },
  { id: "2", name: "Federated Learning Framework", description: "Privacy-preserving distributed ML training across organizational boundaries", program: "AI & Machine Learning", tags: ["AI & Machine Learning", "Privacy", "Distributed Systems"], rdLevel: 72, status: "completed", documentsCount: 8, lastUpdated: "2026-02-20", criteria: criteriaTexts.fl },
  { id: "3", name: "LLM Fine-tuning Pipeline", description: "Domain-specific fine-tuning of large language models for legal document analysis", program: "AI & Machine Learning", tags: ["AI & Machine Learning", "NLP", "Legal Tech"], status: "analyzing", documentsCount: 5, lastUpdated: "2026-03-01" },
  { id: "4", name: "Explainable AI Module", description: "Interpretability layer for black-box models in regulated industries", program: "AI & Machine Learning", tags: ["AI & Machine Learning", "Compliance"], rdLevel: 88, status: "completed", documentsCount: 15, lastUpdated: "2026-01-15", criteria: { novelty: "The project develops a novel layer-wise relevance propagation variant specifically designed for transformer architectures in regulatory contexts. This extends existing XAI methods by incorporating domain-specific constraints from financial and healthcare regulations into the explanation generation process, which has not been previously attempted at this level of integration.", uncertainty: "Significant uncertainty existed around whether the explanation fidelity could be maintained while meeting regulatory requirements for deterministic outputs. The team discovered that standard attention-based explanations were insufficient for audit trails, requiring fundamental research into alternative attribution methods.", creativity: "The creative innovation lies in formulating regulatory compliance requirements as constraints within the explanation optimization problem, allowing the system to generate explanations that are simultaneously faithful to the model's reasoning and compliant with specific regulatory frameworks.", systematic: "Research followed a rigorous validation protocol involving domain experts from three regulated industries. Each explanation method was evaluated against ground-truth annotations from human experts, with inter-annotator agreement metrics used to establish baselines.", transferable: "The regulatory-aware XAI framework is designed to be model-agnostic and has been validated across multiple architectures. The constraint formulation approach could be extended to other domains requiring auditable AI decision-making." } },
  { id: "5", name: "Solid-State Battery Prototype", description: "Next-gen solid-state lithium batteries with improved energy density", program: "Green Energy", tags: ["Green Energy", "Battery Tech", "Materials"], rdLevel: 76, status: "completed", documentsCount: 20, lastUpdated: "2026-02-10", criteria: { novelty: "The project investigates a new class of sulfide-based solid electrolytes with modified crystal structures that show improved ionic conductivity at room temperature. While solid-state batteries are an active research area, the specific dopant combinations explored here have not been reported in the literature.", uncertainty: "Major uncertainties included whether the modified electrolyte would maintain structural stability during cycling and whether the interface resistance between the electrolyte and lithium metal anode could be reduced to practical levels. Multiple synthesis approaches were attempted before achieving stable interfaces.", creativity: "The team developed an original combinatorial screening approach for identifying optimal dopant ratios, significantly accelerating the materials discovery process. The approach to interface engineering using in-situ formed interlayers represents a creative solution to the dendrite penetration problem.", systematic: "The research followed established materials science methodology with systematic variation of synthesis parameters, comprehensive characterization using XRD, SEM, and impedance spectroscopy, and standardized cycling protocols for performance evaluation.", transferable: "The combinatorial screening methodology is applicable to other solid electrolyte systems. The interface engineering approach could be adapted for sodium-ion or potassium-ion solid-state batteries. Detailed synthesis protocols have been documented for reproducibility." } },
  { id: "6", name: "Solar Cell Efficiency Study", description: "Perovskite-silicon tandem cells exceeding 30% efficiency", program: "Green Energy", tags: ["Green Energy", "Solar", "Materials"], rdLevel: 60, status: "completed", documentsCount: 9, lastUpdated: "2026-01-28", criteria: { novelty: "The project optimizes existing perovskite deposition techniques for tandem cell configurations. While achieving 30% efficiency represents a significant engineering accomplishment, the methods employed are largely refinements of established approaches rather than fundamentally new techniques.", uncertainty: "The main uncertainties related to long-term stability of the perovskite layer under thermal cycling and humidity exposure. While these are known challenges in the field, the specific degradation mechanisms observed in the tandem configuration required investigation.", creativity: "The contribution is primarily in the engineering optimization of layer thicknesses and interface treatments rather than conceptually novel approaches. The anti-reflection coating design shows some creative elements in its biomimetic surface texturing.", systematic: "Testing followed standard IEC protocols for solar cell characterization, with accelerated aging tests conducted according to established procedures. However, the experimental design could have been more systematic in exploring the parameter space.", transferable: "The optimized deposition parameters are specific to the particular perovskite composition used. The anti-reflection coating approach could find broader application in other thin-film solar cell technologies." } },
  { id: "7", name: "Hydrogen Storage System", description: "Metal-organic frameworks for ambient hydrogen storage", program: "Green Energy", tags: ["Green Energy", "Hydrogen", "Materials"], status: "draft", documentsCount: 3, lastUpdated: "2026-03-02" },
  { id: "8", name: "mRNA Delivery Mechanism", description: "Lipid nanoparticle optimization for targeted mRNA delivery", program: "Biotech Research", tags: ["Biotech Research", "Drug Delivery", "Nanotech"], rdLevel: 91, status: "completed", documentsCount: 25, lastUpdated: "2026-02-18", criteria: { novelty: "The project introduces a fundamentally new class of ionizable lipids with pH-responsive behavior optimized for endosomal escape. The combinatorial library approach used to discover these lipids is itself novel, employing a machine-learning-guided synthesis strategy that has not been previously reported for lipid nanoparticle design.", uncertainty: "The project faced substantial uncertainties around in-vivo biodistribution, immune response profiles, and whether the enhanced endosomal escape would translate to improved therapeutic efficacy. Multiple formulation iterations were required, with several showing unexpected toxicity profiles that necessitated redesign of the lipid structure.", creativity: "The integration of machine learning with high-throughput lipid synthesis represents a highly creative approach to nanoparticle optimization. The pH-responsive design that mimics viral fusion peptide behavior is a particularly inventive biomimetic strategy.", systematic: "The research followed a comprehensive methodology from computational design through in-vitro screening to in-vivo validation in multiple animal models. Each stage had clearly defined success criteria and the team maintained detailed records enabling full reproducibility.", transferable: "The ML-guided lipid design platform is broadly applicable to other nanoparticle delivery systems. The pH-responsive lipid structures could be adapted for siRNA, DNA, or protein delivery. The methodology has been documented in sufficient detail for technology transfer." } },
  { id: "9", name: "CRISPR Screening Platform", description: "High-throughput CRISPR-based genetic screening for drug targets", program: "Biotech Research", tags: ["Biotech Research", "Genomics", "Drug Discovery"], rdLevel: 82, status: "analyzing", documentsCount: 14, lastUpdated: "2026-02-25", criteria: { novelty: "The platform introduces a new guide RNA design algorithm that reduces off-target effects while maintaining on-target efficiency. The integration of single-cell readouts with pooled screening represents an advance over existing approaches, though individual components build on established CRISPR screening methodologies.", uncertainty: "Key uncertainties included whether the improved guide RNA design would maintain its advantages across different cell types and whether the single-cell integration would provide actionable insights beyond what bulk screening reveals. Results showed cell-type-dependent performance that requires further investigation.", creativity: "The approach of combining spatial transcriptomics with CRISPR perturbation to create a spatially-resolved functional genomics platform is creative and opens new experimental possibilities not available with existing screening approaches.", systematic: "The platform development followed a systematic validation pipeline with positive and negative control genes, cross-validation across cell lines, and comparison with published screening datasets. Statistical frameworks for hit calling were rigorously developed.", transferable: "The guide RNA design algorithm is applicable to any CRISPR screening application. The analytical pipeline for single-cell CRISPR screens has been packaged as an open-source software tool." } },
  { id: "10", name: "Synthetic Biology Toolkit", description: "Standardized biological parts for synthetic organism design", program: "Biotech Research", tags: ["Biotech Research", "Synthetic Biology"], rdLevel: 74, status: "completed", documentsCount: 11, lastUpdated: "2026-01-30", criteria: { novelty: "The toolkit standardizes existing biological parts using a new characterization framework that enables more predictable behavior in combinatorial assemblies. While standardization efforts exist (e.g., BioBricks), the quantitative characterization approach and the predictive models for part interactions represent a meaningful advance.", uncertainty: "The primary uncertainty was whether parts characterized in isolation would behave predictably when combined in complex circuits. The team discovered significant context-dependent effects that required developing new models for part-part interactions.", creativity: "The project creatively addresses the composability problem by introducing insulator elements that buffer parts from context effects, drawing inspiration from electronic circuit design principles applied to biological systems.", systematic: "Parts were characterized using standardized protocols across multiple host organisms. Each part was measured under defined conditions with sufficient replicates for statistical confidence. The characterization data is structured in a machine-readable database.", transferable: "The characterization framework and insulator elements are designed for broad use by the synthetic biology community. The database format follows emerging community standards for biological part data sharing." } },
  { id: "11", name: "Graphene Composite", description: "Graphene-reinforced polymer composites for aerospace applications", program: "Advanced Materials", tags: ["Advanced Materials", "Aerospace", "Nanotech"], rdLevel: 79, status: "completed", documentsCount: 16, lastUpdated: "2026-02-05", criteria: { novelty: "The project develops a new surface functionalization method for graphene sheets that improves dispersion in epoxy matrices. While graphene composites are widely studied, the specific functionalization chemistry using plasma-assisted grafting represents a new approach that achieves superior filler-matrix adhesion compared to existing methods.", uncertainty: "Uncertainties included whether the functionalization would survive processing temperatures and whether the improved dispersion would translate to macroscopic mechanical property improvements. The scale-up from lab-scale to prepreg manufacturing introduced additional unknowns.", creativity: "The plasma-assisted functionalization approach is a creative adaptation of semiconductor processing techniques to composite materials. The use of gradient functionalization to create tailored interfaces between graphene and matrix is an original concept.", systematic: "The research followed standard composite characterization protocols (ASTM standards) with systematic variation of functionalization parameters and filler loading. Mechanical testing was comprehensive, including tensile, flexural, impact, and fatigue testing.", transferable: "The functionalization technique is applicable to other 2D nanomaterials such as boron nitride or MoS2. The gradient interface concept could be applied to other composite systems. Processing parameters have been documented for industrial adoption." } },
  { id: "12", name: "Self-Healing Polymer", description: "Autonomous damage repair in structural polymer matrices", program: "Advanced Materials", tags: ["Advanced Materials", "Smart Materials"], rdLevel: 63, status: "draft", documentsCount: 4, lastUpdated: "2026-03-03", criteria: { novelty: "The project proposes a vascular self-healing approach using microchannels filled with healing agents. While vascular self-healing has been demonstrated previously, the proposed use of UV-curable healing agents for aerospace applications has some novel elements related to the curing mechanism in dark environments.", uncertainty: "Preliminary testing has raised questions about healing agent stability over extended periods and whether the microchannel network can be reliably manufactured at production scale. These are significant unresolved uncertainties that will require substantial experimental work.", creativity: "The proposed dual-healing mechanism combining capsule-based and vascular approaches shows creative thinking about redundancy in self-healing systems. The concept of using shape-memory polymers to mechanically close cracks before chemical healing is innovative.", systematic: "The project is early-stage with a well-structured research plan but limited experimental results to date. The proposed characterization methodology is appropriate but needs to be executed.", transferable: "If successful, the dual-healing approach could be applied to other structural applications such as wind turbine blades, automotive components, or civil infrastructure." } },
];
